#!/usr/bin/env python3
"""Render a typed name as a cursive signature SVG. Used by the name-signature skill.

Pure stdlib: no fonts, no image libraries, no network. Letterforms are composed from a
small vocabulary of cursive gestures (hump, bowl, ascender loop, descender loop), chained
into one continuous pen stroke, smoothed with Catmull-Rom, slanted, then emitted as a
variable-width filled outline so downstrokes read heavier than cross-strokes.

Deterministic: the same name and style always produce byte-identical SVG, because the
hand-wobble is seeded from a SHA-256 of the name rather than from a random source.
"""

import hashlib
import math
import sys

# Geometry in em units, y pointing UP with the baseline at y=0.
XH = 1.0      # x-height
ASC = 1.95    # ascender height (l, b, d, h, k)
DESC = -0.80  # descender depth (g, j, p, q, y)
CAP = 2.35    # capital height
LIGATURE = 0.20  # baseline gap between letters, spanned by a connecting stroke
CAPTION = "Generated by MCP Team"  # set to "" to sign without an attribution line

STYLES = {
    #          slant  x-height(px)  weight  wobble  flourish  stretch
    # `weight` is in pixels; keep it near 0.09 * x-height or the bowls fill in.
    "flowing": (0.26, 36.0, 3.4, 0.034, True, 1.30),
    "compact": (0.13, 32.0, 2.9, 0.020, False, 1.10),
    "bold":    (0.22, 40.0, 5.0, 0.040, True, 1.35),
}


# --------------------------------------------------------------------------- gestures
# Every gesture starts on the baseline at x=0 and ends on the baseline at x=advance,
# so consecutive gestures chain into one unbroken cursive stroke.

def _hump(w, h=XH, pointed=False):
    """Up-stroke, over the shoulder, back down: n m u v w r i."""
    if pointed:
        return [(0.0, 0.0), (w * 0.30, h * 0.62), (w * 0.50, h), (w * 0.70, h * 0.55), (w, 0.0)]
    return [(0.0, 0.0), (w * 0.16, h * 0.70), (w * 0.40, h),
            (w * 0.70, h * 0.80), (w * 0.84, h * 0.30), (w, 0.0)]


def _bowl(w, h=XH):
    """Closed counterclockwise oval with a stem down the right: a d g o q.

    The oval has to actually close, or it reads as a hump and every vowel in the
    name looks like an `n`.
    """
    return [(0.0, 0.0), (w * 0.52, h * 0.28), (w * 0.74, h * 0.70), (w * 0.56, h * 0.99),
            (w * 0.22, h * 0.93), (w * 0.07, h * 0.50), (w * 0.19, h * 0.11),
            (w * 0.49, h * 0.05), (w * 0.73, h * 0.36), (w * 0.79, h * 0.74),
            (w * 0.86, h * 0.30), (w, 0.0)]


def _hook(w, h=XH):
    """Open C-shaped bowl, left side only: c and (shorter) e."""
    return [(0.0, 0.0), (w * 0.58, h * 0.30), (w * 0.72, h * 0.78), (w * 0.46, h * 0.99),
            (w * 0.14, h * 0.72), (w * 0.13, h * 0.24), (w * 0.44, h * 0.04),
            (w * 0.78, h * 0.22), (w, 0.0)]


def _eye(w, h=XH * 0.68):
    """Small forward loop crossing itself: e."""
    return [(0.0, 0.0), (w * 0.30, h * 0.42), (w * 0.72, h * 0.68), (w * 0.60, h * 0.98),
            (w * 0.26, h * 0.80), (w * 0.24, h * 0.30), (w * 0.60, h * 0.10), (w, 0.0)]


def _ess(w, h=XH):
    """Pointed peak with a tucked belly: s."""
    return [(0.0, 0.0), (w * 0.44, h * 0.44), (w * 0.66, h * 0.96), (w * 0.34, h * 0.92),
            (w * 0.26, h * 0.48), (w * 0.62, h * 0.30), (w * 0.52, h * 0.04), (w, 0.0)]


def _loop_up(h=ASC, w=0.34):
    """Ascender loop: up the left side, over the top, down the right side."""
    return [(0.0, 0.0), (w * 1.05, h * 0.42), (w * 0.45, h),
            (0.0, h * 0.80), (w * 0.30, h * 0.30), (w * 0.85, 0.0)]


def _loop_down(d=DESC, w=0.36):
    """Descender loop: down, swing left, loop back up through the baseline."""
    return [(0.0, 0.0), (w * 0.42, d * 0.55), (w * 0.10, d),
            (-w * 0.55, d * 0.70), (-w * 0.10, d * 0.12), (w * 0.90, 0.0)]


def _stem(h, w=0.20):
    """Straight ascender or descender with no loop: t (short), q (down)."""
    return [(0.0, 0.0), (w * 0.55, h * 0.55), (w * 0.75, h), (w * 0.95, h * 0.5), (w * 1.15, 0.0)]


def _shift(points, dx):
    return [(x + dx, y) for x, y in points]


def _chain(*gestures):
    """Concatenate gestures left to right; returns (points, advance)."""
    points: list[tuple[float, float]] = []
    x = 0.0
    for pts in gestures:
        points.extend(_shift(pts, x))
        x += pts[-1][0]
    return points, x


# --------------------------------------------------------------------------- glyphs
# Each entry returns (points, advance, lifts) where `lifts` are separate pen strokes
# (i/j dots, t/f/x cross-bars) drawn after the main stroke.

def _glyph(ch: str):
    if ch == "a":
        return (*_chain(_bowl(0.66)), [])
    if ch == "o":
        return (*_chain(_bowl(0.62)), [])
    if ch == "c":
        return (*_chain(_hook(0.56)), [])
    if ch == "e":
        return (*_chain(_eye(0.46)), [])
    if ch == "s":
        return (*_chain(_ess(0.44)), [])
    if ch == "n":
        return (*_chain(_hump(0.62)), [])
    if ch == "m":
        return (*_chain(_hump(0.58), _hump(0.58)), [])
    if ch == "u":
        return (*_chain(_hump(0.58), _hump(0.30, XH * 0.55)), [])
    if ch == "v":
        return (*_chain(_hump(0.52, pointed=True), _hump(0.22, XH * 0.5, pointed=True)), [])
    if ch == "w":
        return (*_chain(_hump(0.48, pointed=True), _hump(0.48, pointed=True),
                        _hump(0.20, XH * 0.5, pointed=True)), [])
    if ch == "r":
        return (*_chain(_hump(0.36, XH * 0.86), _hump(0.30, XH * 0.42)), [])
    if ch == "l":
        return (*_chain(_loop_up()), [])
    if ch == "b":
        return (*_chain(_loop_up(), _bowl(0.50)), [])
    if ch == "h":
        return (*_chain(_loop_up(), _hump(0.56)), [])
    if ch == "k":
        return (*_chain(_loop_up(), _hump(0.30, XH * 0.55), _hump(0.30, XH * 0.42)), [])
    if ch == "d":
        return (*_chain(_bowl(0.58), _loop_up(ASC * 0.92)), [])
    if ch == "t":
        pts, adv = _chain(_stem(ASC * 0.80))
        bar = [(adv * 0.05, XH * 1.12), (adv * 1.05, XH * 1.22)]
        return pts, adv, [bar]
    if ch == "f":
        pts, adv = _chain(_loop_up(ASC), _loop_down(DESC * 0.85))
        bar = [(adv * 0.02, XH * 0.78), (adv * 0.85, XH * 0.90)]
        return pts, adv, [bar]
    if ch == "g":
        return (*_chain(_bowl(0.58), _loop_down()), [])
    if ch == "y":
        return (*_chain(_hump(0.52), _loop_down()), [])
    if ch == "j":
        pts, adv = _chain(_hump(0.26, XH * 0.80), _loop_down())
        return pts, adv, [[(adv * 0.28, XH * 1.30), (adv * 0.40, XH * 1.34)]]
    if ch == "p":
        return (*_chain(_loop_down(DESC * 0.95), _bowl(0.52)), [])
    if ch == "q":
        return (*_chain(_bowl(0.58), _stem(DESC * 1.05)), [])
    if ch == "z":
        return (*_chain(_hump(0.44, XH * 0.82, pointed=True), _loop_down(DESC * 0.85)), [])
    if ch == "i":
        pts, adv = _chain(_hump(0.34, XH * 0.80))
        return pts, adv, [[(adv * 0.34, XH * 1.28), (adv * 0.46, XH * 1.32)]]
    if ch == "x":
        pts, adv = _chain(_hump(0.44, XH * 0.86, pointed=True))
        return pts, adv, [[(0.02, XH * 0.88), (adv * 0.96, XH * 0.06)]]
    # Unknown letter: a neutral hump keeps the stroke flowing rather than breaking it.
    return (*_chain(_hump(0.50)), [])


def _capital(ch: str):
    """A capital is an enlarged glyph with a lead-in flourish from below the baseline."""
    pts, adv, lifts = _glyph(ch.lower())
    scale = CAP / XH * 0.62
    pts = [(x * scale * 1.05, y * scale) for x, y in pts]
    lifts = [[(x * scale * 1.05, y * scale) for x, y in lift] for lift in lifts]
    lead = [(-0.30, -0.18), (-0.12, CAP * 0.30), (0.02, CAP * 0.62)]
    return lead + pts, adv * scale * 1.05, lifts


# --------------------------------------------------------------------------- curves
def _wobble(seed_text: str):
    """Endless deterministic stream of jitter in [-0.5, 0.5], seeded from the name."""
    digest = hashlib.sha256(seed_text.encode("utf-8")).digest()
    index = 0
    while True:
        yield digest[index] / 255.0 - 0.5
        index += 1
        if index == len(digest):
            digest = hashlib.sha256(digest).digest()
            index = 0


def _catmull(p0, p1, p2, p3, t):
    """Uniform Catmull-Rom point at t in [0, 1) on the p1 -> p2 segment."""
    t2, t3 = t * t, t * t * t
    return tuple(
        0.5 * (2 * b + (-a + c) * t + (2 * a - 5 * b + 4 * c - d) * t2 + (-a + 3 * b - 3 * c + d) * t3)
        for a, b, c, d in zip(p0, p1, p2, p3)
    )


def _smooth(points, per_segment=16):
    """Dense sample of the Catmull-Rom spline through `points`."""
    if len(points) < 2:
        return list(points)
    padded = [points[0]] + list(points) + [points[-1]]
    out = []
    for i in range(len(padded) - 3):
        p0, p1, p2, p3 = padded[i:i + 4]
        out.extend(_catmull(p0, p1, p2, p3, k / per_segment) for k in range(per_segment))
    out.append(points[-1])
    return out


def _outline(samples, weight, thin=0.34):
    """Variable-width pen outline: heavy on vertical motion, light on horizontals."""
    if len(samples) < 2:
        return []
    left, right = [], []
    last = len(samples) - 1
    taper = max(1.0, last * 0.07)
    for i, (x, y) in enumerate(samples):
        ax, ay = samples[max(0, i - 1)]
        bx, by = samples[min(last, i + 1)]
        dx, dy = bx - ax, by - ay
        length = math.hypot(dx, dy) or 1e-9
        tx, ty = dx / length, dy / length
        half = weight * (thin + (1.0 - thin) * abs(ty)) / 2.0
        half *= min(1.0, 0.22 + 0.78 * min(i, last - i) / taper)  # taper both ends
        left.append((x - ty * half, y + tx * half))
        right.append((x + ty * half, y - tx * half))
    return left + right[::-1]


def _esc(text: str) -> str:
    """Escape text for use in XML content or a double-quoted attribute."""
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def _path(points, precision=2):
    if not points:
        return ""
    head = f"M {points[0][0]:.{precision}f} {points[0][1]:.{precision}f}"
    rest = " ".join(f"L {x:.{precision}f} {y:.{precision}f}" for x, y in points[1:])
    return f"{head} {rest} Z"


# --------------------------------------------------------------------------- render
def signature_svg(name: str, style: str = "flowing", color: str = "#1a2b4c",
                  caption: str = CAPTION) -> str:
    """Return a standalone SVG string of `name` written as a cursive signature.

    `caption` is set beneath the signature as an attribution line; pass "" to omit it.
    """
    if style not in STYLES:
        raise ValueError(f"unknown style {style!r}; choose from {', '.join(STYLES)}")
    slant, unit, weight, wobble_amp, flourish, stretch = STYLES[style]
    jitter = _wobble(f"{name}|{style}")

    strokes: list[list[tuple[float, float]]] = []
    lifts: list[list[tuple[float, float]]] = []
    run: list[tuple[float, float]] = []
    pen_x = 0.0

    for word_index, word in enumerate(name.split()):
        if word_index:  # word gap breaks the stroke, as a real hand lifts between words
            if run:
                strokes.append(run)
                run = []
            pen_x += 0.55
        for char_index, char in enumerate(word):
            if not char.isalpha():
                pen_x += 0.30
                continue
            builder = _capital if (char.isupper() and char_index == 0) else _glyph
            pts, advance, extra = builder(char)
            # Per-letter hand-wobble: vertical drift plus a slight size breath.
            drift = next(jitter) * wobble_amp * 2.2
            breath = 1.0 + next(jitter) * wobble_amp
            if run:  # ligature: a short rising connector into this letter's entry
                run.append((pen_x - LIGATURE * 0.55, 0.17))
            pts = [(pen_x + x * stretch, y * breath + drift) for x, y in pts]
            run.extend(pts)
            lifts.extend(
                [[(pen_x + x * stretch, y * breath + drift) for x, y in e] for e in extra]
            )
            pen_x += advance * stretch + LIGATURE
    if run:
        strokes.append(run)
    if not strokes:
        # Digits and punctuation advance the pen without drawing, so a name made only of
        # them would otherwise emit a lone flourish and look like a valid signature.
        raise ValueError("nothing to draw: the name has no letters")

    if flourish and pen_x > 0:  # terminal swash: sweep right, loop back beneath the name
        lifts.append([
            (pen_x - 0.10, 0.05), (pen_x + 0.55, 0.30), (pen_x + 0.95, -0.05),
            (pen_x + 0.35, -0.40), (-0.20, -0.52), (-0.55, -0.22),
        ])

    # em units -> pixels: slant, flip y, pad.
    pad = unit * 0.55
    def place(points):
        return [((x + y * slant) * unit + pad, -y * unit) for x, y in points]

    shapes = [_outline(_smooth(place(s)), weight) for s in strokes]
    shapes += [_outline(_smooth(place(l)), weight * 0.72) for l in lifts]
    shapes = [s for s in shapes if s]

    ys = [y for shape in shapes for _, y in shape]
    xs = [x for shape in shapes for x, _ in shape]
    top, bottom = min(ys) - pad * 0.4, max(ys) + pad * 0.4
    width = max(xs) + pad

    # Attribution line, set below the lowest ink (descenders and swash included). Drawn
    # as <text> rather than outlined paths: it is a caption, so a system-font fallback is
    # harmless, whereas the signature itself must never depend on a font being present.
    caption_svg = ""
    if caption:
        size = unit * 0.29
        tracking = size * 0.09
        baseline = bottom + size * 1.5
        bottom = baseline + size * 0.42
        # A short name with a long caption would otherwise overflow the viewBox.
        width = max(width, len(caption) * size * 0.56 + tracking * len(caption) + pad * 2)
        caption_svg = (
            f'\n  <text x="{width / 2:.2f}" y="{baseline:.2f}" text-anchor="middle" '
            f'font-family="system-ui, -apple-system, Segoe UI, Roboto, sans-serif" '
            f'font-size="{size:.2f}" letter-spacing="{tracking:.2f}" font-weight="500" '
            f'fill="{color}" fill-opacity="0.55">{_esc(caption)}</text>'
        )

    height = bottom - top
    body = "\n  ".join(f'<path d="{_path(shape)}"/>' for shape in shapes)
    label = f"Signature of {name}" + (f", captioned {caption}" if caption else "")
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width:.0f}" height="{height:.0f}" '
        f'viewBox="0 {top:.2f} {width:.2f} {height:.2f}" role="img" '
        f'aria-label="{_esc(label)}">\n'
        f'  <g fill="{color}" fill-rule="nonzero">\n  {body}\n  </g>{caption_svg}\n</svg>\n'
    )


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print('usage: sign.py <name> [style] [color] [caption]\n'
              '       style: flowing|compact|bold\n'
              f'       caption defaults to "{CAPTION}"; pass "" for none',
              file=sys.stderr)
        raise SystemExit(2)
    who = args[0]
    how = args[1] if len(args) > 1 else "flowing"
    ink = args[2] if len(args) > 2 else "#1a2b4c"
    line = args[3] if len(args) > 3 else CAPTION
    try:
        print(signature_svg(who, how, ink, line), end="")
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
    except BrokenPipeError:
        # Downstream closed the pipe (`sign.py X | head`). Exit quietly instead of
        # letting the interpreter print a traceback at shutdown.
        sys.stderr.close()
        raise SystemExit(0)
